<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZqk2ydm\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZqk2ydm/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerZqk2ydm.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerZqk2ydm\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerZqk2ydm\appProdProjectContainer(array(
    'container.build_hash' => 'Zqk2ydm',
    'container.build_id' => '7facdba5',
    'container.build_time' => 1557914471,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerZqk2ydm');
