<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFrjkuwl\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFrjkuwl/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerFrjkuwl.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerFrjkuwl\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerFrjkuwl\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Frjkuwl',
    'container.build_id' => '5be1e5f3',
    'container.build_time' => 1561677880,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerFrjkuwl');
