<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEnaikdx\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEnaikdx/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerEnaikdx.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerEnaikdx\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerEnaikdx\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Enaikdx',
    'container.build_id' => '3148e201',
    'container.build_time' => 1560807067,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerEnaikdx');
